//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/_MyProject/InputSystem/GameActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace MyProject.Actor
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/_MyProject/InputSystem/GameActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @GameActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @GameActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameActions"",
    ""maps"": [
        {
            ""name"": ""Quad"",
            ""id"": ""3d628d34-7cbc-4a47-9eef-0b318b71426a"",
            ""actions"": [
                {
                    ""name"": ""Lane0"",
                    ""type"": ""Button"",
                    ""id"": ""c2c61ffb-a627-4f9f-8a0c-1299a7bcbd49"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lane1"",
                    ""type"": ""Button"",
                    ""id"": ""dd41d95c-9062-4d39-9f75-5a5e407db403"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lane2"",
                    ""type"": ""Button"",
                    ""id"": ""4c46f443-39be-4126-90c0-f3d14fb3bf01"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lane3"",
                    ""type"": ""Button"",
                    ""id"": ""d4a65985-3677-4a82-9e03-38b00b1e26e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8dfad4ef-cad6-4b52-b9f7-7bdeb7562d45"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lane0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""583b838a-deec-4b13-97b2-44ac9c1466ab"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee1e300-402e-422e-970e-5fe8d65fc4d7"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef965bc6-dbb4-4bfa-8ba4-6a02624ba808"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Quad
            m_Quad = asset.FindActionMap("Quad", throwIfNotFound: true);
            m_Quad_Lane0 = m_Quad.FindAction("Lane0", throwIfNotFound: true);
            m_Quad_Lane1 = m_Quad.FindAction("Lane1", throwIfNotFound: true);
            m_Quad_Lane2 = m_Quad.FindAction("Lane2", throwIfNotFound: true);
            m_Quad_Lane3 = m_Quad.FindAction("Lane3", throwIfNotFound: true);
        }

        ~@GameActions()
        {
            UnityEngine.Debug.Assert(!m_Quad.enabled, "This will cause a leak and performance issues, GameActions.Quad.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Quad
        private readonly InputActionMap m_Quad;
        private List<IQuadActions> m_QuadActionsCallbackInterfaces = new List<IQuadActions>();
        private readonly InputAction m_Quad_Lane0;
        private readonly InputAction m_Quad_Lane1;
        private readonly InputAction m_Quad_Lane2;
        private readonly InputAction m_Quad_Lane3;
        /// <summary>
        /// Provides access to input actions defined in input action map "Quad".
        /// </summary>
        public struct QuadActions
        {
            private @GameActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public QuadActions(@GameActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Quad/Lane0".
            /// </summary>
            public InputAction @Lane0 => m_Wrapper.m_Quad_Lane0;
            /// <summary>
            /// Provides access to the underlying input action "Quad/Lane1".
            /// </summary>
            public InputAction @Lane1 => m_Wrapper.m_Quad_Lane1;
            /// <summary>
            /// Provides access to the underlying input action "Quad/Lane2".
            /// </summary>
            public InputAction @Lane2 => m_Wrapper.m_Quad_Lane2;
            /// <summary>
            /// Provides access to the underlying input action "Quad/Lane3".
            /// </summary>
            public InputAction @Lane3 => m_Wrapper.m_Quad_Lane3;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Quad; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="QuadActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(QuadActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="QuadActions" />
            public void AddCallbacks(IQuadActions instance)
            {
                if (instance == null || m_Wrapper.m_QuadActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_QuadActionsCallbackInterfaces.Add(instance);
                @Lane0.started += instance.OnLane0;
                @Lane0.performed += instance.OnLane0;
                @Lane0.canceled += instance.OnLane0;
                @Lane1.started += instance.OnLane1;
                @Lane1.performed += instance.OnLane1;
                @Lane1.canceled += instance.OnLane1;
                @Lane2.started += instance.OnLane2;
                @Lane2.performed += instance.OnLane2;
                @Lane2.canceled += instance.OnLane2;
                @Lane3.started += instance.OnLane3;
                @Lane3.performed += instance.OnLane3;
                @Lane3.canceled += instance.OnLane3;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="QuadActions" />
            private void UnregisterCallbacks(IQuadActions instance)
            {
                @Lane0.started -= instance.OnLane0;
                @Lane0.performed -= instance.OnLane0;
                @Lane0.canceled -= instance.OnLane0;
                @Lane1.started -= instance.OnLane1;
                @Lane1.performed -= instance.OnLane1;
                @Lane1.canceled -= instance.OnLane1;
                @Lane2.started -= instance.OnLane2;
                @Lane2.performed -= instance.OnLane2;
                @Lane2.canceled -= instance.OnLane2;
                @Lane3.started -= instance.OnLane3;
                @Lane3.performed -= instance.OnLane3;
                @Lane3.canceled -= instance.OnLane3;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="QuadActions.UnregisterCallbacks(IQuadActions)" />.
            /// </summary>
            /// <seealso cref="QuadActions.UnregisterCallbacks(IQuadActions)" />
            public void RemoveCallbacks(IQuadActions instance)
            {
                if (m_Wrapper.m_QuadActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="QuadActions.AddCallbacks(IQuadActions)" />
            /// <seealso cref="QuadActions.RemoveCallbacks(IQuadActions)" />
            /// <seealso cref="QuadActions.UnregisterCallbacks(IQuadActions)" />
            public void SetCallbacks(IQuadActions instance)
            {
                foreach (var item in m_Wrapper.m_QuadActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_QuadActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="QuadActions" /> instance referencing this action map.
        /// </summary>
        public QuadActions @Quad => new QuadActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Quad" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="QuadActions.AddCallbacks(IQuadActions)" />
        /// <seealso cref="QuadActions.RemoveCallbacks(IQuadActions)" />
        public interface IQuadActions
        {
            /// <summary>
            /// Method invoked when associated input action "Lane0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLane0(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Lane1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLane1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Lane2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLane2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Lane3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLane3(InputAction.CallbackContext context);
        }
    }
}
